config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'sequence#input'

  get 'sequence/input'
  get 'sequence/view'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sequence_controller.rb
# frozen_string_literal: true

# Контроллер для последовательности
class SequenceController < ApplicationController
  def input; end

  def view
    @input = params[:values]&.split&.map { |el| Integer el }
    raise StandardError, 'Seq length is less than 10' if @input.length < 10

    @result = find_increasing_subseq&.map { |subseq| subseq.join(' ') }
  rescue ArgumentError
    @error = 'Некорректный ввод'
  rescue NoMethodError
    @error = 'Последовательность не найдена'
  rescue StandardError
    @error = 'Последовательность короче 10 чисел'
  end

  private

  def find_increasing_subseq
    @input.each_with_object([[]]) do |el, acc|
      acc << [] if el <=> acc[-1][-1] && el <= acc[-1][-1]
      acc[-1] << el
    end.filter { |arr| arr.count > 1 }.yield_self { |this| this.append(this.max_by(&:length)) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sequence_helper.rb
module SequenceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab 8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sequence/input.html.erb
<h1 class="m-3">Поиск последовательности</h1>
<p class="m-3 text-truncate">Будет определена наиболее длинная монотонно возрастающая последовательность чисел.</p>
<div class="w-50">
    <%= form_tag sequence_view_path, method: 'get', class: 'm-3' do %>
            <div class="col-12"><%= label_tag :values, 'Введите последовательность чисел через пробел:' %></div>
            <div class="row mt-2">
                <div class="col-11 p-1 m-0"><%= text_field_tag :values, '', class: 'form-control', required: true %></div>
                <div class="col-1 p-1 m-0"><%= button_tag "Найти", type: 'submit', name: nil, class: 'btn btn-primary' %></div>
            </div>
    <% end %>
</div>

app/views/sequence/view.html.erb
<h1 class="m-3">Результат поиска</h1>

<% if @error %>
    <p class="text-danger m-3"><%= @error %></p>
<% else %>

<div class="m-3">Вы ввели: <%= @input.join(' ') %></div>
<div class="w-25 m-3 table-responsive">
    <table class="table table-striped table-sm table-bordered">
        <thead class="text-center">
            <tr>
                <th scope="col">No.</th>
                <th scope="col">Последовательность</th>
            </tr>
        </thead>
        <tbody>
            <% @result.each.with_index(1) do |subseq, ind| %>
                <tr>
                    <th scope="row" class="col-1 text-center"><%= ind == @result.count ? 'Ответ' : ind %></td>
                    <td><%= subseq %></td></tr>
            <% end %>
        <tbody>
    </table>
</div>
<% end %>
<br>
<button type="button" class="btn btn-link">
    <%= link_to 'Домой', root_path %>
</button>